//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courier_Management_system_Next.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourierManagementsystemNextdbEntities : DbContext
    {
        public CourierManagementsystemNextdbEntities()
            : base("name=CourierManagementsystemNextdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaInfo> AreaInfoes { get; set; }
        public virtual DbSet<BookingDelivareyType> BookingDelivareyTypes { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<deliveryMan> deliveryMen { get; set; }
        public virtual DbSet<siteuser> siteusers { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
